# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('id_number', models.IntegerField(default=0)),
                ('currently_employed', models.CharField(choices=[('Active Employee', 'Active Employee'), ('Deactivated Employee', 'Deactivated Employee')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('created_profile', models.DateTimeField(auto_now_add=True)),
                ('updated_profile', models.DateTimeField(auto_now=True)),
                ('job_description', models.TextField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
