# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
