# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170910_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='slug',
        ),
    ]
