# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20170911_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
