# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_employeedetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
