# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20170912_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='currently_employed',
            field=models.CharField(choices=[('Active Employee', 'Active Employee'), ('Deactivated Employee', 'Deactivated Employee')], default=False, max_length=30),
        ),
    ]
